# Generated by Django 2.0.1 on 2018-01-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_mnt_product_mnt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='contact_mnt',
            name='pid',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product_mnt',
            name='pid',
            field=models.IntegerField(blank=True),
        ),
    ]
