# Generated by Django 2.0.1 on 2018-01-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20180108_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='contact_mnt',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
