# Generated by Django 2.0.1 on 2018-01-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20180108_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_mnt',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_mnt',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
